const tmp_labels = {
  // previously collected labels below:
  xFieldLabel: ["X-field", "X-axel"],
  yFieldLabel: ["Y-field", "Y-axel"],
  colorFieldLabel: ["Color", ""],
  trendFieldLabel: ["Trend", ""],
  trendOverallSlope: ["with slope <", ""],
  trendLogSlope: ["with coeff <", ""],
  trendLastTimeValue: ["with value <", ""],
  showLine: ["Show Lines", ""],
  showAverage: ["Show Municipal Average", ""],
  tenureCheckbox: ["Class/  Tenure View", ""],
  boxToggle: ["Box", ""],
  violinToggle: ["Violin", ""],
  circleToggle: ["Circle", ""],
  presentIndividual: ["Present Individuals", ""],
  connectIndividual: ["Connect Individuals", ""],
  reset: ["Reset", ""],
  resetLatest: ["Reset to latest saved", ""],
  savePreset: ["Save Preset", ""],
  loadPreset: ["Load Preset", ""],
  importData: ["Import Data", ""],
  editConfig: ["Edit Config", ""],
  saveConfig: ["Save Config", ""],
  help: ["Help", ""],
  plotPage: ["Plot", ""],
  helpPage: ["Help", ""],
  aboutPage: ["About", ""],
  logoutPage: ["Logout", ""],
  filterBySchoolandClass: ["Filter by School and Class", ""],
  filterByOptionRange: ["Filter by Option/Range", ""],
  schoolTreeTopLevelTag: ["Schools", ""],
  groupClassBy: ["Group Classes By", ""],
  symbolicFilterTag: [
    'Symbolic Filter, e.g., "Skola.contains Bo AND Lexplore Score > 500"',
    "",
  ],
  aggregateView_X_tag: ["Periods of Testdatum", ""],
  brushTag: ["Brush", ""],
  deBrushTag: ["De-Brush", ""],
  seasonByQuarter: ["Quarter", ""],
  seasonByMonth: ["Month", ""],
  seasonBySemester: ["Semester", ""],
  trendOptionAll: ["all", ""],
  trendOptionDecline: ["overall decline", ""],
  trendOptionLogDecline: ["logarithmicly decline", ""],
  trendOptionLastDecline: ["last time decline", ""],
  groupByNineYear: ["9-year tenure", ""],
  groupByThreeYear: ["3-year tenure", ""],
  groupBySchoolYear: ["school-year", ""],
  groupByTrajectory: ["trajectory", ""],
  // Continue with any additional labels as necessary
};
